### ISSUE TITLE
Feature Request: Additional Output/Logging when KubernetesSecretConfigProvider Fails to Enumerate Values

### ISSUE THREAD

**Issue by daviddyball** [strimzi/kafka-kubernetes-config-provider#31]
I Strimzi crew 👋 Thanks for the great tool(s)!

## Backstory

I was recently pulling my hair out over a `KafkaConnector` not connecting to our brokers. It was complaining about not being authorised to access the subject in Schema Registry. I spent quite a bit of time debugging everything on our clusters and in Kafka, but it wasn't until I took a wild guess and hard-coded my credentials into the `KafkaConnector` manifest that I realised that my `${secret:<namespace>/<name>:<key>}` entries in `spec.config` weren't being templated because we hadn't granted the correct RBAC... in reality the Connector was trying to authenticate with the following literal string in it's configuration:

```
value.converter.basic.auth.user.info=${secret:dev/my-app-secret:userinfo}
```

instead of the expected

```
value.converter.basic.auth.user.info=secret_username:super_secret_password
```

## Request

It'd be really nice if there was some output indicating that the secrets weren't enumerating correctly in my `spec.config`. I'm not super familiar with the inner workings of the codebase, but I assume it'd be additional logging on `KubernetesSecretConfigProvider` and `KubernetesConfigMapConfigProvider`?

Thanks again for the great tool.

**Comment by scholzj** [comment]
What does it mean `KubernetesSecretConfigProvider Fails to Enumerate Values`?

**Comment by daviddyball** [comment]
> What does it mean `KubernetesSecretConfigProvider Fails to Enumerate Values`?

When the operator fails to turn `${secret:namespace/kubernetes-secret:KEY}` into the secret value and instead just uses `${secret:namespace/kubernetes-secret:KEY}` as a literal string.

**Comment by scholzj** [comment]
This is not handled by any operator. This is done by Kafka. So if it was not used properly, I guess you misconfigured something ... for example you didn't properly configure the provider or might have some special characters somewhere? Or Kafka does not support the provider in a place where you are trying to use it.

I have no idea what `value.converter.basic.auth.user.info` is or where it is. So I do not know if it is expected that the configuration providers would work there or not.

In any case, I do not think this is a problem of logging -> when the value stays the same as you entered it, the config provider was likely never called by Kafka. So there is no way it can log something.

**Comment by daviddyball** [comment]
Sorry, my explanation must be lacking.

The specific request is to have any failed invocation of [kafka-kubernetes-config-provider](https://github.com/strimzi/kafka-kubernetes-config-provider) be more verbose when it fails to expand on a `${secrets:......}` string.

**Comment by scholzj** [comment]
But as I said, I don't think there was any failed invocation. Based on what you shared, the provider was likely not called at all.
